import { getPages } from '@/sanity/sanity.utils';
import Link from 'next/link';
import '../globals.css';

export const metadata = {
  title: 'My Awesome Portfolio!',
  description: 'Generated by Next + Sanity'
};

export default async function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  // get all of our pages
  const pages = await getPages();

  return (
    <html lang="en">
      <body className="bg-slate-900 max-w-3xl mx-auto py-10">
        <header className="flex items-center justify-between">
          <Link
            href="/"
            className="bg-gradient-to-r from-orange-400 via-red-500 to-purple-600 bg-clip-text text-transparent text-lg font-bold"
          >
            ⬅️ Renan
          </Link>

          <div className="flex items-center gap-5 text-sm text-white">
            {pages.map(({ _id, title, slug }) => (
              <Link key={_id} href={`/${slug}`} className="hover:underline">
                {title}
              </Link>
            ))}
          </div>
        </header>

        <main className="py-20">{children}</main>
      </body>
    </html>
  );
}
